name: Build and push Docker image

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Get app version
        id: get_version
        run: |
          version=$(./gradlew getVersion | grep -o "Version: [0-9]*\.[0-9]*\.[0-9]*" | awk '{print $2}')
          echo "Version: $version"
          echo "APP_VERSION=$version" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          echo "Building Docker image with version ${{ steps.get_version.outputs.APP_VERSION }}"
          ./gradlew bootBuildImage --imageName=docker.pkg.github.com/${{ github.repository }}/autocentral:${{ steps.get_version.outputs.APP_VERSION }} --tag latest

      - name: Push Docker image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
          docker push docker.pkg.github.com/${{ github.repository }}/autocentral:${{ steps.get_version.outputs.APP_VERSION }}
